kind: Service
apiVersion: v1
metadata:
  name: echo-service
spec:
  selector:
    app: echo-app
  ports:
  - protocol: TCP
    port: 50000
    targetPort: 50000
---
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: echo-service-deployment
  labels:
    app: echo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-app
  template:
    metadata:
      labels:
        app: echo-app
    spec:
      containers:
      - name: echo
        image: hashicorp/http-echo
        ports:
        - containerPort: 50000
        args: ["-text='hello world'", "-listen=:50000"]